## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import sys

def configure(conf):
    # Add the ns3wifi module to the list of enabled modules that
    # should not be built if this is a static build on Darwin.  They
    # don't work there for the ns3wifi module, and this is probably
    # because the ns3wifi module has no source files.
    if conf.env['ENABLE_STATIC_NS3'] and sys.platform == 'darwin':
        conf.env['MODULES_NOT_BUILT'].append('ns3wifi')

def build(bld):
    # Don't do anything for this module if it should not be built.
    if 'ns3wifi' in bld.env['MODULES_NOT_BUILT']:
        return

    ns3wifi = bld.create_ns3_module('ns3wifi', ['internet', 'mobility', 'propagation', 'wifi', 'applications'])
    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'ns3wifi'
    headers.source = [
        'ns3wifi.h',
        ]

    ns3wifi_test = bld.create_ns3_module_test_library('ns3wifi')
    ns3wifi_test.source = [
        'wifi-interference-test-suite.cc',
        'wifi-msdu-aggregator-test-suite.cc',
        ]

