## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('nix-vector-routing', ['internet-stack', 'contrib'])
    module.includes = '.'
    module.source = [
        'ipv4-nix-vector-routing.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'nix-vector-routing'
    headers.source = [
        'ipv4-nix-vector-routing.h',
        ]

