## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('l2-routing-main', ['node', 'bridge'])
    obj.source = [
	'l2-routing-net-device.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'l2-routing-main'
    headers.source = [
	'l2-routing-net-device.h',
        ]
