## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('udp-client-server', ['csma', 'internet'])
    obj.source = 'udp-client-server.cc'
    
    obj = bld.create_ns3_program('udp-trace-client-server', ['csma', 'internet', 'applications'])
    obj.source = 'udp-trace-client-server.cc'
