## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('ping6', ['internet-stack'])
    module.source = [
        'ping6.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'ping6'
    headers.source = [
        'ping6.h',
        ]

