## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('topology-read', ['node'])
    obj.source = [
       'topology-reader.cc',
       'inet-topology-reader.cc',
       'orbis-topology-reader.cc',
       'rocketfuel-topology-reader.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'topology-read'
    headers.source = [
       'topology-reader.h',
       'inet-topology-reader.h',
       'orbis-topology-reader.h',
       'rocketfuel-topology-reader.h',
        ]

