## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def configure(conf):
    conf.sub_config('perf')

def build(bld):
    test = bld.create_ns3_module('test', ['core'])
    test.source = [
        'sample-test-suite.cc',
        'error-model-test-suite.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'test'
    headers.source = [
        ]
