## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def configure(conf):
    conf.sub_config('perf')

def build(bld):
    test = bld.create_ns3_module('test', ['internet', 'mobility', 'applications', 'csma', 'bridge', 'config-store', 'tools', 'point-to-point', 'csma-layout'])
    headers = bld.new_task_gen('ns3header')
    headers.module = 'test'

    test_test = bld.create_ns3_module_test_library('test')
    test_test.source = [
        'csma-system-test-suite.cc',
        'global-routing-test-suite.cc',
        'static-routing-test-suite.cc',
        'error-model-test-suite.cc',
        'mobility-test-suite.cc',
        ]

