## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('energy', ['node'])
    obj.source = [
        'model/wifi-radio-energy-model.cc',
        'model/energy-source.cc',
        'model/basic-energy-source.cc',
        'model/device-energy-model.cc',
        'model/device-energy-model-container.cc',
        'helper/energy-source-container.cc',
        'helper/energy-model-helper.cc',
        'helper/basic-energy-source-helper.cc',
        'helper/wifi-radio-energy-model-helper.cc',
        'test/basic-energy-model-test.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'energy'
    headers.source = [
        'model/wifi-radio-energy-model.h',
        'model/energy-source.h',
        'model/basic-energy-source.h',
        'model/device-energy-model.h',
        'model/device-energy-model-container.h',
        'helper/energy-source-container.h',
        'helper/energy-model-helper.h',
        'helper/basic-energy-source-helper.h',
        'helper/wifi-radio-energy-model-helper.h',
        ]
