## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    module = bld.create_ns3_module('virtual-net-device', ['node'])
    module.source = [
        'virtual-net-device.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'virtual-net-device'
    headers.source = [
        'virtual-net-device.h',
        ]

