## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    # Don't build any examples unless they are enabled.
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    # Uncomment these lines to build this C++ example program.
    #program = bld.create_ns3_program('sample-example', ['core'])
    #program.source = 'sample-example.cc'

    # Uncomment this line to register the dependencies for this Python
    # example script.
    #bld.register_ns3_script('sample-example.py', ['core'])
