## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('socket-bound-static-routing', ['node', 'csma', 'internet-stack'])
    obj.source = 'socket-bound-static-routing.cc'

    obj = bld.create_ns3_program('socket-bound-tcp-static-routing', ['node', 'csma', 'internet-stack'])
    obj.source = 'socket-bound-tcp-static-routing.cc'
