## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def configure(conf):
    pass

def build(bld):
    ns3tcp = bld.create_ns3_module('ns3tcp')
    headers = bld.new_task_gen('ns3header')
    headers.module = 'ns3tcp'
    headers.source = [
        'ns3tcp.h',
        ]
    ns3tcp.source = [
        'ns3tcp-socket-writer.cc',
        'ns3tcp-loss-test-suite.cc',
        ]
    if bld.env['NSC_ENABLED']:
        ns3tcp.source.append ('ns3tcp-interop-test-suite.cc')
        ns3tcp.source.append ('ns3tcp-cwnd-test-suite.cc')
        ns3tcp.source.append ('ns3tcp-socket-test-suite.cc')
