7## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program( 'wimax-ipv4', ['wimax', 'internet', 'mobility', 'csma'])
    obj.source = 'wimax-ipv4.cc'

    obj = bld.create_ns3_program( 'wimax-multicast', ['wimax', 'internet', 'csma'])
    obj.source = 'wimax-multicast.cc'
        
    obj = bld.create_ns3_program( 'wimax-simple', ['wimax', 'internet', 'mobility'])
    obj.source = 'wimax-simple.cc'
