## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('virtual-net-device', ['point-to-point', 'internet-stack', 'global-routing', 
                                                        'virtual-net-device'])
    obj.source = 'virtual-net-device.cc'
