## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('nix-simple',
                                 ['point-to-point', 'applications', 'internet', 'nix-vector-routing'])
    obj.source = 'nix-simple.cc'

    obj = bld.create_ns3_program('nms-p2p-nix',
                                 ['point-to-point', 'applications', 'internet', 'nix-vector-routing'])
    obj.source = 'nms-p2p-nix.cc'
