@node Propagation Loss Models
@chapter Propagation Loss Models
@anchor{chap:propagation-loss-models}

This chapter describes validation of ns-3 propagation loss models.

@section FriisPropagationLossModel

@subsection Model reference 

From source: @uref{http://www.scribd.com/doc/6650712/Wireless-CommunicationsPrinciples-and-Practice-Theodore-S,, Wireless Communications-Principles and Practice ,Theodore S Rappaport  pg. 71 }

Given equation:
@verbatim
Pr = Pt*Gt*Gr*lmb^2/((4*pi)^2*d^2*L)

Pt = 10^(17.0206/10)/10^3 = .05035702 
Pr = .05035702*.125^2/((4*pi)^2*d*1) = 4.98265e-6/d^2

bandwidth = 2.2*10^7 
m_noiseFigure = 5.01187 
noiseFloor = ((Thermal noise (K)* BOLTZMANN * bandwidth)* m_noiseFigure) 
noiseFloor = ((290*1.3803*10^-23*2.2*10^7)*5.01187) = 4.41361e-13W 
no interference, so SNR = Pr/4.41361e-13W

Distance  ::  	Pr		::	SNR 
100		4.98265e-10W		1128.93 
500		1.99306e-11W		45.1571 
1000		4.98265e-12W		11.2893 
2000		1.24566e-12W		2.82232 
3000		5.53628e-13W		1.25436 
4000		3.11416e-13W		0.70558 
5000		1.99306e-13W		0.451571 
6000		1.38407e-13W		0.313591 
@end verbatim

@subsection Validation test

Test program available online at: @uref{http://xxx.xxx.com,,}

Taken at default settings (packetSize = 1000, numPackets = 1, lambda = 0.125, 802.11b at 2.4GHz):
@verbatim
Distance   ::   Pr		    ::	SNR 
100		4.98265e-10W		1128.93 
500		1.99306e-11W		45.1571 
1000		4.98265e-12W		11.2893 
2000		1.24566e-12W		2.82232 
3000		5.53628e-13W		1.25436 
4000		3.11416e-13W		0.70558 
5000		1.99306e-13W		0.451571 
6000		1.38407e-13W		0.313591 
7000		1.01687e-13W		0.230393 
8000		7.78539e-14W		0.176395
@end verbatim

@subsection Discussion

As can be seen, the SNR outputted from the simulator, and the SNR computed from the source's equation are identical.

@section LogDistancePropagationLossModel

@subsection Model reference

From source: @uref{http://www.plextek.co.uk/papers/aps2005mcw.pdf,, Urban Propagation Measurements and Statistical Path Loss Model at 3.5 GHz, Marcus C. Walden, Frank J. Rowsell}

Given equation:
@verbatim
PL{dBm} = PL(d0) + 10*n*log(d/d0) + Xs

PL(1) from friis at 2.4GHz: 40.045997dBm
PL{dBm} = 10*log(.050357/Pr) = 40.045997 + 10*n*log(d) + Xg 
Pr = .050357/(10^((40.045997 + 10*n*log(d) + Xg)/10))

bandwidth = 2.2*10^7 
m_noiseFigure = 5.01187 
no interference, so SNR = Pr/4.41361e-13W 
@end verbatim

taking Xg to be constant at 0 to match ns-3 output:
@verbatim
Distance   ::   Pr 		::	SNR
10		4.98265e-9		11289.3 
20		6.22831e-10		1411.16 
40		7.78539e-11		176.407 
60		2.30678e-11		52.2652 
80		9.73173e-12		22.0494 
100		4.98265e-12		11.2893 
200		6.22831e-13		1.41116 
500		3.98612e-14		.090314 
1000		4.98265e-15		.011289
@end verbatim

@subsection Validation test

Test program available online at: @uref{http://xxx.xxx.com,,}

Taken at default settings (packetSize = 1000, numPackets = 1, exponent = 3, reference loss = 46.6777, 802.11b at 2.4GHz)
@verbatim
Distance   ::   Pr		::	snr 
10		4.98471e-9		11293.9 
20		6.23089e-10		1411.74 
40		7.78861e-11		176.468 
60		2.30774e-11		52.2868 
80		9.72576e-12		22.0585 
100		4.98471e-12		11.2939 
200		6.23089e-13		1.41174 
500		3.98777e-14		0.0903516 
1000		4.98471e-15		0.0112939
@end verbatim


@subsection Discussion
There is a ~.04% error between these results. I do not believe this is 
due to rounding, as the results taken from the equation from the source 
match exactly with the Friis results taken at one less power of ten. 
(Friis and LogDistance can be modeled by Pt*Gt*Gr*lmb^2/((4*pi)^2*d^n*L), 
where n is the exponent. n is 2 for Friis, and 3 for logDistance, which 
accounts for the power of ten. ie: Friis at 100m is equivalent to LogDistance 
at 10m.)  Perhaps the ns-3 takes the random number into account despite 
not being listed in the source.

