@node Propagation Loss Models
@chapter Propagation Loss Models
@anchor{chap:propagation-loss-models}

This chapter describes validation of ns-3 propagation loss models.

@section FriisPropagationLossModel

@subsection Model reference 

From source: @uref{http://www.scribd.com/doc/6650712/Wireless-CommunicationsPrinciples-and-Practice-Theodore-S,, Wireless Communications-Principles and Practice ,Theodore S Rappaport  pg. 71 }

Given equation:
@smallformat
@verbatim
Pr = Pt*Gt*Gr*lmb^2/((4*pi)^2*d^2*L)

Pt = 10^(17.0206/10)/10^3 = .05035702 
Pr = .05035702*.125^2/((4*pi)^2*d*1) = 4.98265e-6/d^2

bandwidth = 2.2*10^7 
m_noiseFigure = 5.01187 
noiseFloor = ((Thermal noise (K)* BOLTZMANN * bandwidth)* m_noiseFigure) 
noiseFloor = ((290*1.3803*10^-23*2.2*10^7)*5.01187) = 4.41361e-13W 
no interference, so SNR = Pr/4.41361e-13W

Distance  ::  	Pr		::	SNR 
100		4.98265e-10W		1128.93 
500		1.99306e-11W		45.1571 
1000		4.98265e-12W		11.2893 
2000		1.24566e-12W		2.82232 
3000		5.53628e-13W		1.25436 
4000		3.11416e-13W		0.70558 
5000		1.99306e-13W		0.451571 
6000		1.38407e-13W		0.313591 
@end verbatim
@end smallformat

@subsection Validation test

Test program available in ns-3 at @code{src/devices/wifi/propagation-loss-model-test-suite.cc}

Taken with values (lambda = 0.125m for 802.11b at 2.4GHz, SystemLoss = 1):
@smallformat
@verbatim
Distance   ::   Pr		    
100		4.98265e-10W		
500		1.99306e-11W		
1000		4.98265e-12W		
2000		1.24566e-12W		
@end verbatim
@end smallformat

@subsection Discussion

As can be seen, the received power outputted from the model, and the power 
computed from the source's equation are identical.  The test suite tests 
the expected value to the most significant digit of the input expected value.

@section LogDistancePropagationLossModel

@subsection Model reference

From source: @uref{http://www.plextek.co.uk/papers/aps2005mcw.pdf,, Urban Propagation Measurements and Statistical Path Loss Model at 3.5 GHz, Marcus C. Walden, Frank J. Rowsell}

Given equation:
@smallformat
@verbatim
PL{dBm} = PL(d0) + 10*n*log(d/d0) + Xs

PL(1) from friis at 2.4GHz: 40.045997dBm
PL{dBm} = 10*log(.050357/Pr) = 40.045997 + 10*n*log(d) + Xg 
Pr = .050357/(10^((40.045997 + 10*n*log(d) + Xg)/10))

bandwidth = 2.2*10^7 
m_noiseFigure = 5.01187 
no interference, so SNR = Pr/4.41361e-13W 
@end verbatim

taking Xg to be constant at 0 to match ns-3 output:
@verbatim
Distance   ::   Pr 		::	SNR
10		4.98265e-9		11289.3 
20		6.22831e-10		1411.16 
40		7.78539e-11		176.407 
60		2.30678e-11		52.2652 
80		9.73173e-12		22.0494 
100		4.98265e-12		11.2893 
200		6.22831e-13		1.41116 
500		3.98612e-14		.090314 
1000		4.98265e-15		.011289
@end verbatim
@end smallformat

@subsection Validation test

Test program available in ns-3 at @code{src/devices/wifi/propagation-loss-model-test-suite.cc}

Taken at default settings (exponent = 3, reference loss = 46.6777, 802.11b at 2.4GHz)
@smallformat
@verbatim
Distance   ::   Pr		
10		4.98265e-9		
20		6.22831e-10		
40		7.78539e-11		
80		9.73173e-12		
@end verbatim
@end smallformat

@subsection Discussion
As can be seen, the received power outputted from the model, and the power computed from the source's equation are identical.  The test suite tests 
the expected value to the most significant digit of the input expected value.

