## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('packet-sink', ['node'])
    module.source = [
        'packet-sink.cc',
        ]
    headers = bld.create_obj('ns3header')
    headers.module = 'packet-sink'
    headers.source = [
        'packet-sink.h',
        ]

