## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('dumbbell-animation',
                                 ['netanim', 'applications', 'point-to-point-layout'])
    obj.source = 'dumbbell-animation.cc'

    obj = bld.create_ns3_program('grid-animation',
                                 ['netanim', 'applications', 'point-to-point-layout'])
    obj.source = 'grid-animation.cc'

    obj = bld.create_ns3_program('star-animation',
                                 ['netanim', 'applications', 'point-to-point-layout'])
    obj.source = 'star-animation.cc'
