## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('dpd', ['contrib'])
    module.includes = '.'
    module.source = [
        'id-cache.cc',
		'dpd.cc'
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'dpd'
    headers.source = [
        'dpd.h',
        'id-cache.h',
        ]

