## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('aodv', ['internet-stack', 'contrib'])
    module.includes = '.'
    module.source = [
        'aodv-rtable.cc',
        'aodv-rqueue.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'aodv'
    headers.source = [
        'aodv-rtable.h',
        'aodv-rqueue.h',
        ]

