## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('uan-cw-example', ['core', 'simulator', 'mobility', 'uan'])
    obj.source = 'uan-cw-example.cc'

    obj = bld.create_ns3_program('uan-rc-example', ['core', 'simulator', 'mobility', 'uan'])
    obj.source = 'uan-rc-example.cc'
