## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def configure(conf):
    conf.env.append_value('NS3_MODULES', 'ns3-applications')


def build(bld):
    obj = bld.create_obj('cpp', 'shlib')
    obj.name = 'ns3-applications'
    obj.target = obj.name
    obj.uselib_local = ['ns3-node']
    obj.source = [
        'onoff-application.cc',
        ]

    headers = bld.create_obj('ns3header')
    headers.source = [
        'onoff-application.h',
        ]
