## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('topology-read', ['network'])
    obj.source = [
       'model/topology-reader.cc',
       'model/inet-topology-reader.cc',
       'model/orbis-topology-reader.cc',
       'model/rocketfuel-topology-reader.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'topology-read'
    headers.source = [
       'model/topology.h',
       'model/topology-reader.h',
       'model/inet-topology-reader.h',
       'model/orbis-topology-reader.h',
       'model/rocketfuel-topology-reader.h',
        ]

