## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    module = bld.create_ns3_module('emulated', ['node'])
    module.source = [
        'emulated-net-device.cc',
        ]
    headers = bld.create_obj('ns3header')
    headers.module = 'emulated'
    headers.source = [
        'emulated-net-device.h',
        ]

