## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    # Create the module with the appropriate name and the list of
    # modules it depends on.
    module = bld.create_ns3_module('template', ['core'])

    # Set the C++ source files for this module.
    module.source = [
        # Uncomment these lines to compile these model source files.
        #'model/sample-model-1.cc',
        #'model/sample-model-2.cc',

        # Uncomment these lines to compile these helper source files.
        #'helper/sample-helper-1.cc',
        #'helper/sample-helper-2.cc',
        ]

    # Create the module's test library.
    module_test = bld.create_ns3_module_test_library('template')

    # Set the C++ source files for the module's test library.
    module_test.source = [
        # Uncomment these lines to compile these test suites.
        #'test/sample-test-suite-1.cc',
        #'test/sample-test-suite-2.cc',
        ]

    # Make headers be installed for this module.
    headers = bld.new_task_gen('ns3header')
    headers.module = 'template'

    # Set the C++ header files for this module.
    headers.source = [
        # Uncomment these lines to install these model header files.
        #'model/sample-model-1.h',
        #'model/sample-model-2.h',

        # Uncomment these lines to install these helper header files.
        #'helper/sample-helper-1.h',
        #'helper/sample-helper-2.h',
        ]

    # Uncomment these lines if this module needs a library such as the
    # real-time (RT) library to be linked in at build time.
    #module     .uselib = 'RT'
    #module_test.uselib = 'RT'

    # Look for examples if they are enabled. 
    if (bld.env['ENABLE_EXAMPLES']):
        bld.add_subdirs('examples')
