## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('simple-point-to-point-olsr',
                                 ['point-to-point', 'internet-stack', 'olsr'])
    obj.source = 'simple-point-to-point-olsr.cc'

    obj = bld.create_ns3_program('olsr-hna',
                                 ['core', 'simulator', 'mobility', 'wifi'])
    obj.source = 'olsr-hna.cc'
