# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('wave-simple-80211p',
        ['core', 'applications', 'mobility', 'network', 'wifi','wave'])
    obj.source = 'wave-simple-80211p.cc'
