#! /usr/bin/env python
## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# A list of C++ examples to run in order to ensure that they remain
# buildable and runnable over time.  Each tuple in the list contains
#
#     (example_name, do_run, do_valgrind_run).
#
# See test.py for more information.
cpp_examples = [
    ("wifi-phy-configuration --testCase=0", "True", "True"),
    ("wifi-phy-configuration --testCase=1", "True", "True"),
    ("wifi-phy-configuration --testCase=2", "True", "True"),
    ("wifi-phy-configuration --testCase=3", "True", "True"),
    ("wifi-phy-configuration --testCase=4", "True", "True"),
    ("wifi-phy-configuration --testCase=5", "True", "True"),
    ("wifi-phy-configuration --testCase=6", "True", "True"),
    ("wifi-phy-configuration --testCase=7", "True", "True"),
    ("wifi-phy-configuration --testCase=8", "True", "True"),
    ("wifi-phy-configuration --testCase=9", "True", "True"),
    ("wifi-phy-configuration --testCase=10", "True", "True"),
    ("wifi-phy-configuration --testCase=11", "True", "True"),
    ("wifi-phy-configuration --testCase=12", "True", "True"),
    ("wifi-phy-configuration --testCase=13", "True", "True"),
    ("wifi-phy-configuration --testCase=14", "True", "True"),
    ("wifi-phy-configuration --testCase=15", "True", "True"),
    ("wifi-phy-configuration --testCase=16", "True", "True"),
    ("wifi-phy-configuration --testCase=17", "True", "True"),
    ("wifi-phy-configuration --testCase=18", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11a --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11b --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11g --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11-holland --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11-10MHz --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11-5MHz --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=0 --nss=2 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=1 --nss=4 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=0 --nss=1 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=1 --nss=1 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=0 --nss=1 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=1 --nss=1 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=1 --nss=4 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=0 --nss=2 --stepTime=0.1", "True", "True"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
    ("minstrel-ht-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=4 --stepTime=0.1", "True", "True"),
# To be uncommented once fix for bug 2647 is delivered
#    ("ideal-wifi-manager-example --standard=802.11a --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11b --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11g --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11-holland --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11-10MHz --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11-5MHz --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=0 --nss=2 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=20 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-5GHz --channelWidth=40 --shortGuard=1 --nss=4 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=0 --nss=1 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=1 --nss=1 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=0 --nss=1 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=1 --nss=1 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=20 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11n-2.4GHz --channelWidth=40 --shortGuard=1 --nss=4 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=1 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=0 --nss=2 --stepTime=0.1", "True", "True"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=2 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=3 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=20 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=40 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=80 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=0 --nss=4 --stepTime=0.1", "False", "False"),
#    ("ideal-wifi-manager-example --standard=802.11ac --channelWidth=160 --shortGuard=1 --nss=4 --stepTime=0.1", "True", "True"),
]

# A list of Python examples to run in order to ensure that they remain
# runnable over time.  Each tuple in the list contains
#
#     (example_name, do_run).
#
# See test.py for more information.
python_examples = []
