/* -*-  Mode: C++; c-file-style: "gnu"; indent-tabs-mode:nil; -*- */
/*
 * Copyright (c) 2005 INRIA
 * All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as 
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Mathieu Lacage <mathieu.lacage@sophia.inria.fr>
 */

#include "mac-high-adhoc.h"
#include "dca-txop.h"
#include "wifi-net-device.h"
#include "ns3/packet.h"

#define noADHOC_TRACE 1

#ifdef ADHOC_TRACE
# include <iostream>
# define TRACE(x) \
  std::cout << "HIGH ADHOC "<<x<<std::endl;
#else /* ADHOC_TRACE */
# define TRACE(x)
#endif /* ADHOC_TRACE */

namespace ns3 {

MacHighAdhoc::MacHighAdhoc ()
{}
MacHighAdhoc::~MacHighAdhoc ()
{}

void
MacHighAdhoc::SetInterface (WifiNetDevice *interface)
{
  m_interface = interface;

}
void 
MacHighAdhoc::SetForwardCallback (ForwardCallback callback)
{
  m_callback = callback;
}
void
MacHighAdhoc::SetDcaTxop (DcaTxop *dca)
{
  m_dca = dca;
}

Mac48Address 
MacHighAdhoc::GetBssid (void) const
{
  // XXX the bssid should be generated by the procedure
  // described in ieee802.11 section 11.1.3
  return Mac48Address::GetBroadcast ();
}

void 
MacHighAdhoc::Enqueue (Packet packet, Mac48Address to)
{
  TRACE ("enqueue size="<<packet.GetSize ()<<", to="<<to<<
         ", queueSize="<<m_queue->GetSize ());
  WifiMacHeader hdr;
  hdr.SetType (WIFI_MAC_DATA);
  hdr.SetAddr1 (to);
  hdr.SetAddr2 (m_interface->GetSelfAddress ());
  hdr.SetAddr3 (m_interface->GetBssid ());
  hdr.SetDsNotFrom ();
  hdr.SetDsNotTo ();
  m_dca->Queue (packet, hdr);
}

void 
MacHighAdhoc::Receive (Packet packet, WifiMacHeader const *hdr)
{
  TRACE ("received size="<<packet.GetSize ()<<", from="<<hdr->GetAddr2 ());
  m_callback (packet);
}

}; // namespace ns3
