## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
import os.path

def build(bld):
    env = bld.env

    unit_tests = bld.create_ns3_program('run-tests', ['common'])
    unit_tests.install_path = None # do not install
    unit_tests.source = 'run-tests.cc'
    ## link unit test program with all ns3 modules
    unit_tests.uselib_local = 'ns3'
    
    obj = bld.create_ns3_program('bench-simulator', ['simulator'])
    obj.source = 'bench-simulator.cc'

    obj = bld.create_ns3_program('bench-packets', ['common'])
    obj.source = 'bench-packets.cc'

    obj = bld.create_ns3_program('print-introspected-doxygen',
                                 ['internet-stack', 'csma-cd', 'point-to-point'])
    obj.source = 'print-introspected-doxygen.cc'

