## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('wifi-phy-test',
        ['core', 'mobility', 'network', 'wifi'])
    obj.source = 'wifi-phy-test.cc'

    obj = bld.create_ns3_program('test-interference-helper',
        ['core', 'mobility', 'network', 'wifi'])
    obj.source = 'test-interference-helper.cc'
