## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('csma', ['node'])
    obj.source = [
        'backoff.cc',
        'csma-net-device.cc',
        'csma-channel.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'csma'
    headers.source = [
        'backoff.h',
        'csma-net-device.h',
        'csma-channel.h',
        ]
