## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('onoff', ['core'])
    module.source = [
        'onoff-application.cc',
        ]
    headers = bld.create_obj('ns3header')
    headers.source = [
        'onoff-application.h',
        ]

