## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('three-gpp-http-example', ['applications','point-to-point','internet','network'])
    obj.source = 'three-gpp-http-example.cc'
