## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def configure(conf):
    pass

def build(bld):
    obj = bld.create_ns3_module('perf')
    headers = bld.new_task_gen('ns3header')
    headers.module = 'perf'

    obj = bld.create_ns3_program('perf-io', ['core'])
    obj.source = 'perf-io.cc'


