## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def configure(conf):
    pass

def build(bld):
    obj = bld.create_ns3_program('perf-io')
    obj.source = 'perf-io.cc'


