## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('bridge', ['node'])
    obj.source = [
        'bridge-net-device.cc',
        'bridge-channel.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'bridge'
    headers.source = [
        'bridge-net-device.h',
        'bridge-channel.h',
        ]
