## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    module = bld.create_ns3_module('antenna', ['core'])

    module.source = [
        'model/angles.cc',
        'model/antenna-model.cc',
        'model/isotropic-antenna-model.cc',	
        'model/cosine-antenna-model.cc',
        'model/parabolic-antenna-model.cc',
	 ]		
	 
    module_test = bld.create_ns3_module_test_library('antenna')
    module_test.source = [
        'test/test-angles.cc',
        'test/test-degrees-radians.cc',
        'test/test-isotropic-antenna.cc',
        'test/test-cosine-antenna.cc',
        'test/test-parabolic-antenna.cc',
        ]
    
    headers = bld(features='ns3header')
    headers.module = 'antenna'
    headers.source = [
        'model/angles.h',
        'model/antenna-model.h',
        'model/isotropic-antenna-model.h',		
        'model/cosine-antenna-model.h',
        'model/parabolic-antenna-model.h',
	]

    bld.ns3_python_bindings()
