## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('udp-echo', ['internet-stack'])
    module.source = [
        'udp-echo-client.cc',
        'udp-echo-server.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'udp-echo'
    headers.source = [
        'udp-echo-client.h',
        'udp-echo-server.h',
        ]

