# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('traci-applications', ['core', 'wifi', 'applications', 'mobility','internet', 'config-store','stats', 'traci', 'applications'])
    module.source = [
        'model/traffic-control-app.cc',
        'helper/traffic-control-app-helper.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'traci-applications'
    headers.source = [
        'model/traffic-control-app.h',
        'helper/traffic-control-app-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

