## -*-Mode : python; py-indent-offset : 4; indent-tabs-mode : nil; coding : utf-8; -*-

import wutils

# Required NetAnim version
NETANIM_RELEASE_NAME = "netanim-3.106"


def build (bld) :
	module = bld.create_ns3_module ('netanim', ['internet', 'mobility', 'wimax', 'wifi', 'csma', 'lte', 'uan', 'energy'])
	module.includes = '.'
	module.source = [
			  'model/animation-interface.cc',
		        ]
    	netanim_test = bld.create_ns3_module_test_library('netanim')
    	netanim_test.source = [
        	'test/netanim-test.cc',
        ]

	headers = bld(features='ns3header')
	headers.module = 'netanim'
	headers.source = [
			  'model/animation-interface.h',
  			 ]

	if (bld.env['ENABLE_EXAMPLES']) :
		bld.recurse('examples')

