## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('netanim', ['internet', 'mobility'])
    module.includes = '.'
    module.source = [
        'model/animation-interface.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'netanim'
    headers.source = [
        'model/animation-interface.h',
        ]

    if (bld.env['ENABLE_EXAMPLES']):
        bld.add_subdirs('examples')

    bld.ns3_python_bindings()


def configure(conf):
    conf.check(header_name='sys/socket.h', define_name='HAVE_SYS_SOCKET_H')
    conf.check(header_name='netinet/in.h', define_name='HAVE_NETINET_IN_H')

