## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('adhoc-aloha-ideal-phy',
                                 ['spectrum', 'mobility', 'internet', 'applications'])
    obj.source = 'adhoc-aloha-ideal-phy.cc'

    obj = bld.create_ns3_program('adhoc-aloha-ideal-phy-matrix-propagation-loss-model',
                                 ['spectrum', 'mobility', 'internet', 'applications'])
    obj.source = 'adhoc-aloha-ideal-phy-matrix-propagation-loss-model.cc'

    obj = bld.create_ns3_program('adhoc-aloha-ideal-phy-with-microwave-oven',
                                 ['spectrum', 'mobility', 'internet', 'applications'])
    obj.source = 'adhoc-aloha-ideal-phy-with-microwave-oven.cc'


