## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('propagation', ['network', 'mobility'])
    module.includes = '.'
    module.source = [
        'model/propagation-delay-model.cc',
        'model/propagation-loss-model.cc',
        'model/jakes-propagation-loss-model.cc',
        'model/cost231-propagation-loss-model.cc',
        ]

    module_test = bld.create_ns3_module_test_library('propagation')
    module_test.source = [
        'test/propagation-loss-model-test-suite.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'propagation'
    headers.source = [
        'model/propagation-delay-model.h',
        'model/propagation-loss-model.h',
        'model/jakes-propagation-loss-model.h',
        'model/cost231-propagation-loss-model.h',
        ]

    if (bld.env['ENABLE_EXAMPLES']):
        bld.add_subdirs('examples')

    bld.ns3_python_bindings()
