/**
 * \defgroup mobility Mobility
 *
 * The mobility support includes:
 *  - a set of mobility models which are used to track and maintain
 *    the "current" cartesian position and speed of an object.
 *
 *  - a "course change notifier" which can be used to register listeners
 *    to the course changes of a mobility model: ns3::MobilityModelNotifier.
 *
 *  - a set of topology constructors which are used to set the initial
 *    position and associate a specific mobility model to a set of objects.
 *
 * The mobility models themselves are:
 *   - StaticMobilityModel: a model which maintains a constant position
 *     until it is changed by the user.
 *
 *   - StaticSpeedMobilityModel: a model which maintains a constant speed
 *     until it is changed by the user.
 *
 *   - HierarchicalMobilityModel: a model which calculates the current 
 *     absolute position from a "reference" (parent) mobility model
 *     and a "relative" (child) mobility model. This allows users to
 *     compose mobility models.
 *
 *   - RandomWalk2dMobilityModel: a 2d "brownian" motion mobility model
 *     where the bounds of the mobility area are a rectangle.
 *
 *   - RandomWaypointMobilityModel: a 3d random waypoint mobility model.
 *
 *   - RandomDirection2dMobilityModel: a 2d random direction mobility
 *     model where the bounds of the mobility are are a rectangle.
 *
 * The topology constructors:
 *   - GridTopology: layout objects in a 2d grid.
 *
 *   - RandomTopology: layout objects in a 3d space, according to a 
 *     RandomPosition model.
 *
 *   - Ns2MobilityFileTopology: layout objects in a 3d space according
 *     to an ns2 CMU mobility file (as generated by the setdest tool).
 */
