## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import os
import sys
import Params

all_modules = [
    'core',
    'common',
    'simulator',
    'node',
    'internet-node',
    'devices/p2p',
    'applications',
    ]


def set_options(opt):
    opt.sub_options('simulator')
    
def configure(conf):
    conf.sub_config('core')
    conf.sub_config('simulator')


def build(bld):
    env = bld.env_of_name('default')
    for module in all_modules:
        node = bld.m_curdirnode.find_dir(module)
        node_path = node.abspath(env)
        env.append_value('NS3_MODULE_PATH', node_path)
    
    bld.add_subdirs(all_modules)
