@node Flow Monitor
@chapter Flow Monitor

@cartouche
Placeholder chapter
@end cartouche

This feature was added as contributed code (@code{src/contrib}) in ns-3.6 and
to the main distribution for ns-3.7.
A paper on this feature is published in the proceedings of NSTools: @*
@uref{http://www.nstools.org/techprog.shtml,,http://www.nstools.org/techprog.shtml}
