@node Statistics
@chapter Statistics

@cartouche
Placeholder chapter
@end cartouche
This wiki page: @*
@uref{http://www.nsnam.org/wiki/index.php/Statistical_Framework_for_Network_Simulation,,http://www.nsnam.org/wiki/index.php/Statistical_Framework_for_Network_Simulation}
contains information about the proposed statistical framework that is 
located in @code{src/contrib} directory.
