# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ns3-sumo-coupling-simple', ['traci-applications', 'wave', 'netanim', 'traci'])
    obj.source = 'ns3-sumo-coupling-simple.cc'

