## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('main-propagation-loss',
                                 ['core', 'mobility', 'config-store', 'stats', 'propagation'])
    obj.source = 'main-propagation-loss.cc'

    obj = bld.create_ns3_program('jakes-propagation-model-example',
                                 ['core', 'propagation'])
    obj.source = 'jakes-propagation-model-example.cc'



