## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    env = bld.env_of_name('default')
    if env['ENABLE_EMU']:
        obj = bld.create_ns3_program('emu-udp-echo', ['emu', 'internet'])
        obj.source = 'emu-udp-echo.cc'

        obj = bld.create_ns3_program('emu-ping', ['emu', 'internet'])
        obj.source = 'emu-ping.cc'
