## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    module = bld.create_ns3_module('tools', ['network', 'stats'])
    module.source = [
        'model/delay-jitter-estimation.cc',
        ]

    module_test = bld.create_ns3_module_test_library('tools')
    module_test.source = [
        'test/average-test-suite.cc',
        ]
    
    headers = bld(features='ns3header')
    headers.module = 'tools'
    headers.source = [
        'model/average.h',
        'model/delay-jitter-estimation.h',
        ]

